name: publish araviq6 to PyPI

on: push

jobs:

  publish:

    runs-on: ubuntu-latest
  
    if: startsWith(github.event.ref, 'refs/tags')
  
    steps:

      - name: get repo
        uses: actions/checkout@v2

      - name: set up Python
        uses: actions/setup-python@v2

      - name: build package
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel

      - name: publish to PyPI
        run: |
          pip install twine
          twine upload dist/* -u __token__ -p ${{ secrets.pypi_token }}
